CREATE TABLE student (rollno number(3) primary key,name varchar(20),age number(2) check(age>=18 and age <=20),city varchar(20) unique,email varchar(20) unique);
insert into student values(1,'ajay',19,'vizag','ajay@gmail.com');
insert into student values(2,'pranav',18,'parvathipuram','pranav@gmail.com');
insert into student values(3,'harsha',20,'vizinagram','harsha@gmail.com');
insert into student values(4,'deepak',20,'salur','deepak@gmail.com');
alter table student add phone number(11);
alter table student modify age number(3);
update student set phone=901777888 where rollno=1; 
update student set phone=901777888 where rollno=2; 
update student set phone=901777888 where rollno=3; 
select *from student;
alter table student drop column phone;
insert into student values(5,'adarsh',20,'vsp','adarsh@gmail.com');
insert into student values(6,'abhijith',22,'ongole','abhi@gmail.com');
select *from student;
delete from student where rollno=1;
truncate table student;
drop table student;
select * from student;
